### ISSUE TITLE
running as a windows services

### ISSUE THREAD

**Issue by TimmyGilissen** [open-telemetry/opentelemetry-collector-releases#214] opened 2022-10-10 12:49 UTC
I'm using nssm to install the otel collector as a windows service.

But every-time the service wants to start it goes in pauze mode.

What i'm i missing to install the collector as a windows service?

Using collector version 0.60.0.

thx
Timmy

**Comment by elitistphoenix** [comment] 2022-10-27 05:53
I'd be interested to know how it installs the service? Maybe a windows registry screenshot? I can't get the service to start from a new-service command in powershell

**Comment by codeboten** [comment] 2022-10-28 16:42
@elitistphoenix if you're running into issues w/ v0.63.0, it's possibly related to https://github.com/open-telemetry/opentelemetry-collector/issues/6433

**Comment by jpkrohling** [comment] 2022-11-30 12:24
I don't think we have any maintainers using Windows, we need your input and engineering help to determine what's the cause and how to fix it.

**Comment by Outek** [comment] 2022-12-15 10:12
I'll try to implement this, we have already some go apps which we install as service on windows.

**Comment by TimmyGilissen** [comment] 2022-12-19 14:10
@Outek that would be awesome thx!

**Comment by simcot** [comment] 2023-05-16 19:55
I'd be interested to know if @Outek had any success in turning the Otel collector into a  windows service as I find myself in the position of using a service creation tool like NSSM 🙏

**Comment by PedroMcj** [comment] 2023-05-17 14:07
Hey @simcot I think I've run into the same problem when using NSSM. After adding the env variable "NO_WINDOWS_SERVICE=1" (as mentioned [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#startup-failing-in-windows-docker-containers) ) to the configuration on NSSM, the new service started correctly. Hope this helps!

**Comment by pjanotti** [comment] 2024-02-05 21:21
@open-telemetry/collector-maintainers I didn't test this on NSSM, I'm not familiar with it, but, I think we can close this one, since detection to run as a service was fixed via #9042

**Comment by mx-psi** [comment] 2024-02-06 10:10
Closing, please file a new issue if you have trouble with running the Collector as a Windows service

**Closed by mx-psi** 2024-02-06 10:10 UTC
Labels: os:windows
