### ISSUE TITLE
Ship Busybox alongside image

### ISSUE THREAD

**Issue by ArthurHenriqueBid** [open-telemetry/opentelemetry-collector-releases#361] opened 2023-06-15 21:19 UTC
My suggestion is to add busybox to the docker image.

**Is your feature request related to a problem? Please describe.**
Yes. In my specific case, I need to fecth an host's apache endpoint and there is no tools inside image to do that. Actually, there isn't any shell at all.

**Describe the solution you'd like**
I would like to have few Linux commands (like wget) available in my container.

**Describe alternatives you've considered**
There is always the approach of making an new Dockerfile using this image as a base and adding what I want, but I will have something like 50 collectors running in a few different datacenters, which made us to choose not going with a custom image.
In this case, we have fixed the issue without fetching the page at all, but busybox would make it so much easier.

**Additional context**
I've spended some time to find that the image doesn't have any shell included. Found it in [this issue](https://github.com/open-telemetry/opentelemetry-collector/issues/3481), which is closed right now. I agree that busybox is well maintained, can be automatically updated with dependabot, is very useful and would not bloat the image at all (at least in my use case). This issue is about kubectl not working well because the image doesn't ship tar executable.

**Comment by jpkrohling** [comment] 2023-06-21 19:49
> I need to fecth an host's apache endpoint

Sorry, can you expand on your use case?

> but I will have something like 50 collectors running in a few different datacenters, which made us to choose not going with a custom image.

I don't know, but I would say that this is a great reason to not only have your own images, but your own distributions.

**Comment by ArthurHenriqueBid** [comment] 2023-06-23 05:03
Hi, sorry about lack of info, i will try to expand more:

I'm running the opentelemetry-collector-contrib image as a docker container inside multiple hosts, using basically hostmetrics receiver in order to get some basic info about the hosts (sending to AMP and showing in Grafana dashboards, everything working here). One of these hosts basically handles an apache server. I can reach the status endpoint using curl inside the network, this handles lots of connections, all running well... But i was trying to test if the container i've 'installed' could reach the endpoint on the host, and how it would go...

I would like to have some basic nix tools inside the container so i can wget some address, for example. Not crucial, but would be good to have. I can simply register and maintain an custom image/dist, as suggested. But i (kind of) could do it because I got an structure, to hold that many hosts, and me as a worker.

That said, I think it would still be good to ship busybox because many people are just learning how to do the tricks with opentelemetry, prometheus, grafana and all of this stuff... I'm in this situation, actually. Most of the people are still learning how to do the tricks with docker, right? I don't know, I just think that this 'ease' would be good specially to reach more people, to make the curve less painful.

P.S.: Also sorry if my english is not good enough for this type of conversation. Sometimes I don't know if I'm sounding too rude or something. Greetings from Brasil!

**Comment by jpkrohling** [comment] 2023-06-23 20:09
> I'm running the opentelemetry-collector-contrib image as a docker container inside multiple hosts

You shouldn't :-) 

> using basically hostmetrics receiver in order to get some basic info about the hosts

Please, build your own image with only the components you need, basically the hostmetrics receiver :-)

> But i was trying to test if the container i've 'installed' could reach the endpoint on the host, and how it would go

Perhaps the host metrics receiver should provide a positive feedback then? But I see what you are doing. In those cases, I just run an ephemeral container on the same namespace, and run ping/dig/curl from there, like:

$ kubectl run curly --image=curlimages/curl -i --tty -- sh

Unless you have a strong reason to run this command from the otelcol container, you will achieve pretty much the same results by doing that.

> That said, I think it would still be good to ship busybox because many people are just learning how to do the tricks with opentelemetry, prometheus, grafana and all of this stuff... 

For Jaeger, we used to have (and perhaps still do) a debug image for that purpose. That one would contain a special binary with the debug symbols in it, as well as dlv in the image, allowing remote debugging of the binary. 

We could start a discussion on having something like that for our images, but I can't commit time to work on this. Would you be open to contributing this? If so, I'll bring this topic to the next SIG meeting.

> P.S.: Also sorry if my english is not good enough for this type of conversation. Sometimes I don't know if I'm sounding too rude or something. Greetings from Brasil!

Você mandou bem, não tive problema nenhum em te entender :-)

**Comment by mx-psi** [comment] 2023-07-05 12:09
Is this a duplicate of #86? Would [`kubectl debug`](https://kubernetes.io/docs/tasks/debug/debug-application/debug-running-pod/#ephemeral-container) help?

**Comment by jpkrohling** [comment] 2023-07-05 12:48
Looks like it is, I'm closing this. This is a cool trick, @mx-psi. Thanks for sharing!

**Closed by jpkrohling** 2023-07-05 12:48 UTC
